scripts/install/debian.sh

- [debian.sh] psutil非默认包，添加入安装脚本中

add pip install psutil

---

class/core/system_api.py

fix: wrong uptime in lxc container

---

plugins/php/versions/52/install.sh
plugins/pureftp/install.sh
route/__init__.py

1.pureftp下载链接切换到github。
2.关闭ssh面板启动尝试链接。
3.优化下载链接。

pureftp下载链接切换到github

---

.github/workflows/python-app-mysql55.yml
.github/workflows/python-app-mysql56.yml
.github/workflows/python-app-mysql57.yml
.github/workflows/python-app-mysql80.yml
.github/workflows/python-app-php.yml
class/core/mw.py

* [优化getLocalIp方法](https://github.com/midoks/mdserver-web/commit/0ea0f2d13dbc8333947341aef8c4eadbde53ba66)

优化getLocalIp方法

---

plugins/rsyncd/install.sh

修复rsyncd在debian或ubuntu下安装失败的bug.

修复rsyncd在debian或ubuntu下安装失败的bug.

---

cmd.md

fix cmd.md

---

class/core/mw.py
plugins/openresty/index.py

修复了反代面板之后保存openresty显示错误的错误

---

README.md
cmd.md
plugins/openresty/index.html
plugins/openresty/index.py
plugins/openresty/js/openresty.js
scripts/install/debian.sh

优化OP反代面板之后显示错误

---

class/core/crontab_api.py
route/static/app/crontab.js

修改计划任务-JS修复

---

class/core/files_api.py
route/static/app/public.js

在线编辑优化-识别其他编码FIX

---

route/__init__.py

为了严格登录，验证码输入错误4次，也直接关闭。

---

plugins/mariadb/info.json
plugins/mariadb/versions/10.6/install.sh
plugins/mariadb/versions/10.7/install.sh
plugins/mariadb/versions/10.8/install.sh
plugins/mariadb/versions/10.9/install.sh
plugins/php/versions/82/install.sh

mariadb版本更新

---

plugins/mariadb/index.py
plugins/mariadb/js/mariadb.js
plugins/mysql/index.py
plugins/mysql/js/mysql.js

mysql和mariadb UI优化

---

plugins/webstats/lua/webstats_common.lua
requirements.txt

fix requirements.txt

---

plugins/mariadb/versions/10.6/install.sh
plugins/mariadb/versions/10.7/install.sh
plugins/mariadb/versions/10.8/install.sh
plugins/mariadb/versions/10.9/install.sh
plugins/mysql/versions/5.5/install.sh
plugins/mysql/versions/5.6/install.sh
plugins/mysql/versions/5.7/install.sh
plugins/mysql/versions/8.0/install.sh
plugins/openresty/install.sh
plugins/php/versions/53/install.sh
plugins/php/versions/54/install.sh
plugins/php/versions/55/install.sh
plugins/php/versions/56/install.sh
plugins/php/versions/70/install.sh
plugins/php/versions/71/install.sh
plugins/php/versions/72/install.sh
plugins/php/versions/73/install.sh
plugins/php/versions/74/install.sh
plugins/php/versions/80/install.sh
plugins/php/versions/81/install.sh
plugins/php/versions/82/install.sh
requirements.txt

优化requirements.txt

---

scripts/install.sh
scripts/install/alma.sh
scripts/install/amazon.sh
scripts/install/arch.sh
scripts/install/centos.sh
scripts/install/debian.sh
scripts/install/fedora.sh
scripts/install/freebsd.sh
scripts/install/opensuse.sh
scripts/install/rhel.sh
scripts/install/rocky.sh
scripts/install/ubuntu.sh

- 国内网络下acme.sh使用离线安装方式
- 把共同的acme.sh安装部分移动到`install.sh`
- 优化了一些系统判断
- 更正了epel国内源

Optimize install scripts

---

class/core/site_api.py

修复子域名绑定没有正常删除问题

---

class/core/cert_api.py
plugins/mongodb/install.sh
plugins/op_waf/conf/luawaf.conf
plugins/op_waf/index.py
plugins/op_waf/info.json
plugins/op_waf/js/op_waf.js
plugins/op_waf/t/index.py
plugins/op_waf/waf/lua/common.lua
plugins/op_waf/waf/lua/init.lua
plugins/op_waf/waf/lua/init_worker.lua
plugins/openresty/conf/lua.conf
plugins/openresty/conf/nginx.conf
plugins/openresty/index.py
plugins/webstats/conf/webstats.conf
plugins/webstats/index.py
plugins/webstats/info.json
plugins/webstats/js/stats.js
plugins/webstats/lua/webstats_common.lua
plugins/webstats/lua/webstats_log.lua
plugins/webstats/tool_task.py

OpenResty配置优化。
如果更新的，OP防火墙和网站统计需要卸载重装一下。
1. OpenResty删除/www/server/openresty/init.d，重启即可。
```
rm -rf /www/server/openresty/init.d
```
2.OP防火墙卸载不成功，需要手动卸载。
```
rm -rf /www/server/op_waf
```
- OP防火墙优化。
- 网站统计优化。

OpenResty配置优化

---

plugins/op_waf/waf/lua/init.lua
plugins/phpmyadmin/index.py

- OP防火墙优化。
- phpmyadmin兼容php-apt/php-yum

 OP防火墙和phpmyadmin轻微优化

---

plugins/php-apt/install.sh
plugins/php-apt/versions/common.sh
plugins/php-apt/versions/phplib.conf
plugins/php-yum/install.sh
plugins/php-yum/versions/74/install.sh
plugins/php-yum/versions/81/install.sh
plugins/php-yum/versions/82/install.sh
plugins/php-yum/versions/common.sh
plugins/php-yum/versions/lib.sh
plugins/php-yum/versions/phplib.conf
plugins/php/install.sh

- php-apt/php-yum安装优化。
- php composer默认安装优化。

php-apt/php-yum安装优化

---

plugins/mysql/index.py

优化mysql初始化

---

plugins/mysql-apt/index.py
plugins/mysql-yum/index.py
route/__init__.py
scripts/update.sh
scripts/update/alma.sh
scripts/update/amazon.sh
scripts/update/arch.sh
scripts/update/centos.sh
scripts/update/debian.sh
scripts/update/fedora.sh
scripts/update/freebsd.sh
scripts/update/opensuse.sh
scripts/update/rhel.sh
scripts/update/rocky.sh
scripts/update/ubuntu.sh
scripts/update_dev.sh

- mysql[apt/yum]迁移功能优化。
- 更新脚本优化。

mysql[apt/yum]迁移功能优化

---

.gitignore
class/core/plugins_api.py
plugins/php-apt/install.sh
plugins/php/versions/common/sg11.sh
plugins/swap/index.html
plugins/webstats/index.html
plugins/webstats/lua/webstats_common.lua
plugins/xhprof/js/xhprof.js
route/static/app/soft.js

- 修复网站统计-设置站点配置产生的问题。
- #337 
- #335 
- php-sg11扩展优化。
- 面板插件优化 - 图标可以自定义。

修复网站统计-设置站点配置产生的问题。

---

plugins/webhook/index.py
plugins/webhook/js/webhook.js
route/__init__.py

修复Webhook 插件BUG

---

app.py
class/core/firewall_api.py
class/core/mw.py
cli.sh
plugins/webhook/install.sh
route/templates/default/layout.html

- 修复iptables和firewalld同时存在，导致识别出错。
- 菜单UI优化。

修复iptables和firewalld同时存在，导致识别出错。

---

class/core/firewall_api.py

- 修复iptables和firewalld同时存在，导致识别出错2。

修复iptables和firewalld同时存在，导致识别出错2。

---

class/core/mw.py
tools.py

优化在命令行下修改端口命令

---

plugins/tgbot/startup/extend/push_ad.py
plugins/tgbot/startup/extend/push_notice_msg.py
scripts/install_dev.sh
scripts/lib.sh

- 修复python pip源安装
- AD
- 安装优化。

修复python pip源安装

---

requirements.txt
version/r3.6.txt

requests兼容低版本

---

class/core/config_api.py
plugins/mariadb/conf/my.cnf
plugins/mariadb/index.html
plugins/mariadb/index.py
plugins/mariadb/js/mariadb.js
plugins/mariadb/versions/10.11/install.sh
plugins/mariadb/versions/10.9/install.sh
plugins/mariadb/versions/11.0/install.sh
plugins/memcached/index.py
plugins/mysql-apt/conf/my5.7.cnf
plugins/mysql-apt/conf/my8.0.cnf
plugins/mysql-apt/index.html
plugins/mysql-apt/index.py
plugins/mysql-apt/install.sh
plugins/mysql-apt/js/mysql-apt.js
plugins/mysql-apt/versions/5.7/install.sh
plugins/mysql-apt/versions/8.0/install.sh
plugins/mysql-yum/conf/my5.7.cnf
plugins/mysql-yum/conf/my8.0.cnf
plugins/mysql-yum/index.html
plugins/mysql-yum/index.py
plugins/mysql-yum/js/mysql-yum.js
plugins/mysql/conf/my5.6.cnf
plugins/mysql/conf/my5.7.cnf
plugins/mysql/conf/my8.0.cnf
plugins/mysql/index.html
plugins/mysql/index.py
plugins/mysql/js/mysql.js
plugins/tgbot/startup/extend/push_ad.py
plugins/tgbot/startup/extend/push_notice_msg.py

- MySQL,MariaDB。
- MySQL-YUM,MYSQL-APT。

MySQL,MariaDB数据库主从同步及多源同步

---

plugins/php/versions/common/gd.sh
plugins/tgbot/startup/extend/init_cmd.py
scripts/init.d/mw.tpl

- 增加清空python库文件(清空后，需要重新生成)。
- php gd安装判断优化。

增加清空python库文件

---

plugins/op_waf/index.py
plugins/op_waf/info.json
plugins/op_waf/install.sh
plugins/op_waf/js/op_waf.js
plugins/op_waf/waf/config.json
plugins/op_waf/waf/lua/init.lua

- 增加了开关-提高效率
-  cd /www/server/mdserver-web/plugins/op_waf && bash install.sh install 0.4.1

OP防火墙-地区限制优化

---

plugins/migration_api/index.py
plugins/mongodb/init.d/mongodb.service.tpl
plugins/php/lib/libmemcached.sh
plugins/php/lib/libsodium.sh
plugins/php/versions/80/install.sh
plugins/php/versions/81/install.sh
plugins/php/versions/82/install.sh
plugins/php/versions/83/install.sh
plugins/php/versions/common/memcached.sh
scripts/install/rhel.sh

- php argon2 安装优化
- 一键迁移优化
- libsodium 安装优化

php argon2 安装优化

---

plugins/dynamic-tracking/install.sh
plugins/mysql/index.py
plugins/op_waf/install.sh
plugins/php/lib/icu.sh
plugins/php/lib/libiconv.sh
plugins/php/lib/libzip.sh
plugins/php/lib/oniguruma.sh
plugins/php/lib/openssl_10.sh
plugins/php/lib/zlib.sh
scripts/install.sh
scripts/install_dev.sh
scripts/lib.sh
scripts/update.sh
scripts/update_dev.sh

更换GitHub Proxy

---

class/core/plugins_api.py
plugins/tgbot/startup/extend/push_ad.py
plugins/tgbot/startup/extend/push_notice_msg.py
scripts/install/debian.sh
scripts/install/ubuntu.sh

- debian/ubuntu 443/udp ufw防火墙默认开启。
- openresty默认安装1.25.3.1。

debian/ubuntu 443/udp ufw防火墙默认开启。

---

class/core/site_api.py
plugins/php/conf/pathinfo.conf

Reverts midoks/mdserver-web#630

Revert "修复http3在多Worker 下需要reuseport以及不传HOST变量的问题"

---

plugins/rsyncd/index.py

rsyncd同步-接收优化2

---

panel_tools.py
plugins/tgbot/startup/extend/push_ad.py
plugins/tgbot/startup/extend/push_notice_msg.py
web/utils/site_reflect.py

- 0.17.0升级0.18.0升级后，站点简单修复。
- mw 29

0.17.0升级0.18.0升级后，站点修复

---

web/utils/file.py

bug! 根目录解压引起所有目录权限发生变化-限制
